variable = 'Hello World'
print(variable[-4])
print(variable[5])
print(variable[4:])
print(variable[4:7])
print(variable[4:8])
print(variable[0:5])
print(variable[:5])
print(variable[-8:-2])
print(len(variable[3]))
print(len(variable))
print(variable[0:9:1])
print(variable[0:9:2])
print(variable[::-1])
print(variable[-1:-10:-1])
