
from collections.abc import Callable


class Animal: ...

class Dog(Animal): ...

class Pitbull(Dog): ...

def handle_pitbull(pitbull: Pitbull) -> None: ...
def handle_dog(dog: Dog) -> None: ...
def handle_animal(animal: Animal) -> None: ...

def handle(handler: Callable[[Dog], None]) -> None: ...

handle(handle_dog)
handle(handle_animal)

# handle(handle_pitbull)
